### ISSUE TITLE
Include BrowserSync

### ISSUE THREAD

**Issue by logeshpaul** [aamirshah/generator-boom#1]
As you are targeting to save developers time by this tool, its good to include BrowserSync to ease responsive testing.

Link - https://github.com/shakyShane/browser-sync
Gulp Setup guide - https://github.com/shakyShane/gulp-browser-sync

**Comment by aamirshah** [comment]
Thanks Logesh for a wonderful suggestion. With [this commit](https://github.com/aamirshah/generator-boom/commit/3b21bdde05a4776885515af4cc3c57ce03d6553e) BrowserSync is now integrated. Don't forget to update Boom to 0.1.4

**Comment by logeshpaul** [comment]
Coolio!
