### ISSUE TITLE
Any way to not concatenate on development build?

### ISSUE THREAD

**Issue by jdpedrie** [aamirshah/generator-boom#14]
Hi,

I was wondering if there is a way to avoid concatenating scripts and stylesheets in development settings. It would be preferable for me if gulp would just add `<script>` and `<link>` tags to all assets unless I explicitly tell it otherwise.

Thanks

**Comment by aamirshah** [comment]
@jdpedrie Yes there is a way Example: `$ yo boom:controller controller_name --add-index`. But as of now its adding `script/...` instead of `js/...` in the index.html file. I'll update you once this is fixed.
