### ISSUE TITLE
gulp fails over missing SETTINGS.src.bower

### ISSUE THREAD

**Issue by Almar** [aamirshah/generator-boom#17]
gulp task 'concat' fails while trying to determine the relative path. Path is relative to SETTINGS.src.bower but this value is undefined.

**Comment by aamirshah** [comment]
@Almar Can you please elaborate your question ? `SETTINGS.src.bower` is not required. Please update `generator-boom`. If your `bower_components` exists in the root folder of the your project then there should be no issues.

**Comment by Almar** [comment]
@aamirshah I have installed generator-boom again and had another try. This time without problems. I guess I hit a glitch the previous time.
