### ISSUE TITLE
Getting 404 Error for generated _bower.css

### ISSUE THREAD

**Issue by sebastianoe** [aamirshah/generator-boom#18]
Directly after having created a project with the boom generator and running it via gulp, I'm getting a 404 for `http://localhost:9000/bower/_bower.css` on the "Sample home template" page which is opened at the end of the default gulp pipeline.
It turns out that the file won't be generated into the _build/bower/_ directory.
It seems to be that there simply isn't a CSS file by default, so that the _bower.css isn't generated. However, the 404 for the default case isn't optimal.

**Comment by aamirshah** [comment]
@sebastianoe  Bower CSS `_bower.css` will be generated only if you have any Bower module which has CSS files associated with it. Example: run `bower install normalize-css --save` and then `gulp`. Now you will see that `_bower.css` will be generated. 

If you don't have any `_bower.css`, then remove it from `index.html`
