### ISSUE TITLE
gulp.run() has been deprecated

### ISSUE THREAD

**Issue by Pierohub** [aamirshah/generator-boom#2]
Hello,
Nice work for this generator. I'm using Gulp 3.5.2 and i have this notice : 

``` js
gulp.run() has been deprecated. Use task dependencies or gulp.watch task triggering instead.
```

I think there's a lot of things to modify in the gulpfile.js but do you have any solution for this issue ?

**Comment by aamirshah** [comment]
Hi, Thanks for the feedback. The only reason I'm using `gulp.run()` is to run few lines of code before actually running the task (E.g. console.log()... etc). Can you suggest some alternate way so that I can still run few lines of code before actually running the task ?

**Comment by Pierohub** [comment]
Hi, I would suggest to regroup copy, concat and watch for each kind of files : css, js, images and html (https://github.com/christophrumpel/blog-gulp-setup/blob/master/Gulpfile.js).
For the "production mode" and console.log issue, I think using functions is a good solution, like this huge example : https://gist.github.com/OverZealous/8343073

**Comment by aamirshah** [comment]
This looks quite interesting. I'll definitely look into it and update you in few days.. :)

**Comment by aamirshah** [comment]
Hi, sorry for the late response.

I've almost revamped the gulpfile. I've used `task dependencies` and `gulp.watch task triggering` and now my gulpfile looks very clean and organised. But I'm facing one issue before I can push the code.

```
gulp.task('build', function(){
        isProduction = false;
        runSequence('copy', 'concat', 'watch');
    });
```

Instead of using gulp.run(), I'm using [runSequesnce](https://www.npmjs.org/package/run-sequence). What is your suggestion on runSequence() ?

**Comment by Pierohub** [comment]
Hello,
I am also using runSequence, but you could simply use gulp.task with dependencies like this: 

``` js
gulp.task('concat', ['copy']);
gulp.task('watch', ['concat']);
gulp.task('build', ['watch']);
```

and for production mode, you can call a parameter like it is mentioned here : https://github.com/orchestrator/orchestrator/issues/17#issuecomment-32114248

``` js
gulp build --type production
```

It is an idea, but I think runSequence is not too bad...

**Comment by aamirshah** [comment]
Hey, Thanks for the suggestion. I found one awesome example [on official docs](https://github.com/gulpjs/gulp/blob/master/docs/recipes/pass-params-from-cli.md) for passing in parameter from `cli`. Its all done I'll close this issue today itself :)

**Comment by aamirshah** [comment]
With this [commit](https://github.com/aamirshah/generator-boom/commit/38686137a55d7e6a7db7fdc25868763adbcc53d5) this issue is fixed.

Don't forget to update Boom to 0.1.5

**Comment by deiga** [comment]
@aamirshah You went and added new `gulp.run(` calls even though it's deprecated, please fix :)
