### ISSUE TITLE
default app not even building

### ISSUE THREAD

**Issue by e-oz** [aamirshah/generator-boom#27]
1. create new app
2. run 'gulp build'

```
/app/js/app.js
  line 7  col 48  Strings must use singlequote.
  line 7  col 62  Strings must use singlequote.
  line 7  col 73  Strings must use singlequote.
  line 7  col 86  Strings must use singlequote.

✖ 4 problems
```

**Comment by aamirshah** [comment]
@jamm  What exactly do you mean by 'not even building' Is the code breaking ?  Or you are referring to the JSHint issues in the generated code ?

**Comment by e-oz** [comment]
Yes, and you can't build project because of these issues.

**Comment by aamirshah** [comment]
@jamm How can jsHint warnings stop you from building the project ? I think I'm not able to get your point, can you please explain in detail.

**Comment by e-oz** [comment]
@aamirshah well, how it usually happens. Build stops after JSHint warnings.
Try to generate new project and run gulp build - project will not be built.
Here is full output:

```
OZ-book:b OZ$ gulp build
[23:05:57] Using gulpfile ~/repositories/b/gulpfile.js
[23:05:57] Starting 'build'...
-------------------------------------------------- BUILD - Development Mode
[23:05:57] Starting 'copy:html'...
-------------------------------------------------- COPY :html
[23:05:57] Finished 'copy:html' after 195 ms
[23:05:57] Starting 'copy:images'...
-------------------------------------------------- COPY :images
[23:05:57] Finished 'copy:images' after 1.26 ms
[23:05:57] Starting 'copy:fonts'...
-------------------------------------------------- COPY :fonts
[23:05:57] Finished 'copy:fonts' after 533 μs
[23:05:57] Starting 'copy:html:root'...
-------------------------------------------------- COPY :html:root
[23:05:57] Finished 'copy:html:root' after 897 μs
[23:05:57] Starting 'copy'...
[23:05:57] Finished 'copy' after 5.08 μs
[23:05:57] Starting 'concat:bower'...
-------------------------------------------------- CONCAT :bower
[23:05:57] Starting 'js:hint'...
-------------------------------------------------- JS - HINT
[23:05:57] Starting 'convert:scss'...
-------------------------------------------------- COVERT - scss
[23:05:57] Finished 'build' after 594 ms

/Users/OZ/repositories/b/app/js/app.js
  line 7  col 47  Strings must use singlequote.
  line 7  col 61  Strings must use singlequote.
  line 7  col 72  Strings must use singlequote.
  line 7  col 85  Strings must use singlequote.

✖ 4 problems

[23:05:57] Finished 'js:hint' after 279 ms
[23:05:57] Starting 'concat:js'...
-------------------------------------------------- CONCAT :js
[23:05:57] Finished 'concat:js' after 2.24 ms
[23:05:57] Finished 'convert:scss' after 155 ms
[23:05:57] Starting 'concat:css'...
-------------------------------------------------- CONCAT :css 
[23:05:57] Finished 'concat:css' after 22 ms
[23:05:57] Finished 'concat:bower' after 573 ms
[23:05:57] Starting 'concat'...
[23:05:57] Finished 'concat' after 9.68 μs
[23:05:57] Starting 'watch'...
watching all the files.....
[23:05:57] Finished 'watch' after 144 ms
```

And nothing else happens. In build folder I see parts of non-minified code, so build process, obviously, was not finished correctly.

**Comment by aamirshah** [comment]
@jamm This is the expected behaviour. You can try opening the localhost:9000 and it will work. There are 2 different tasks `gulp build` and `gulp`. I guess what you are expecting will come from the task `gulp`.

For the jsHint issues, I'll definitely fix it.

**Comment by e-oz** [comment]
@aamirshah no, nothing on 9000 port.

**Comment by aamirshah** [comment]
@jamm Oops, my bad. `gulp build` will only compile the code and throw it to `build` folder. It will watch for the changes and will update the `build` folder. There will be no server fired up.

To fire up the server you need to use either `gulp` or `gulp prod`

**Comment by e-oz** [comment]
@aamirshah ok, got it, but I think it worth to be documented at least.
And still question, why code is not minified after build.

**Comment by aamirshah** [comment]
@jamm The code will be minified only if you want to run in production mode. Use `gulp build:prod` instead of `gulp build`

btw, most of the times you will either use `gulp` or `gulp prod`, I'll work on the documentation.
