### ISSUE TITLE
default app looks too simple

### ISSUE THREAD

**Issue by e-oz** [aamirshah/generator-boom#28]
Well, I try to not use word 'ugly' because I don't want to offend you, but...
![screenshot 2014-08-23 01 45 00](https://cloud.githubusercontent.com/assets/526352/4017921/b9de2f10-2a45-11e4-85a9-15b948d657fc.png)

**Comment by aamirshah** [comment]
@jamm Strange. The left side gray colored div is un-expected. Is its coming automatically or have you added this div.

The expected thing is only 2 lines which are coming on the right hand side.

**Comment by e-oz** [comment]
@aamirshah gray area is just Chrome's background in 'mobile emulation' mode, I did it to make image smaller. Sorry for not mentioning it.

**Comment by aamirshah** [comment]
@jamm So what is the problem then. What else are you expecting ? However cool you make the sample app, nobody will actually use it. And moreover everyone will then have to delete the code to start their own project.

**Comment by e-oz** [comment]
Well, at least it will show that JS and CSS connected. Ok, it's up to you.
