### ISSUE TITLE
bower workflow

### ISSUE THREAD

**Issue by jojoyuji** [aamirshah/generator-boom#3]
Hi Aamir, 

I got some time to look into your super awesome generator!

Everything is working good so far. The only thing I still **haven't figured out is the bower workflow**.

I've installed a couple of angular modules: 
`bower install angular-ui-utils --save` (seems yo can't find this package by itself on its bootstrap) 
`bower install angular-ui-router#0.2.8-bowratic-tedium --save` 

then I run `gulp bower`

but it doesn't concat in _bower.js

Am I missing something? 

Also another suggestion is to not inject $rootScope on it's generator template.

I like the "unused" option set on my jshint config, so I have to remove manually everytime I create a directive/service/controller the `$rootScope` var. 

As I have to inject manually the services I'm using, why not inject $rootScope manually too? 

haha yeah, I know I'm lazy ;)

[Here are some reasons to not declare a var and not use it](http://ariya.ofilabs.com/2012/11/polluting-and-unused-javascript-variables.html)

Awesome work BTW. I hope it become popular!

**Comment by aamirshah** [comment]
Hi Jojo,

Unfortunately bower-concat plugin is not available in Gulp. So I'm calling the Grunt bower-concat from the Gulp file. Now once you add a new module and you want that to be included in you project you will need to add the name of the library in `bower_concat` inside `Gruntfile.js`

The reason this is not automated is that you may have several things downloaded in your bower-components and then you don't want all to be integrated. Or probably you may keep on toggling different libraries. (You comments on this ?)

`$rootScope`, I'll change it in the next commit :)

**Comment by jojoyuji** [comment]
Ah, that's why grunt is still hanging around then.

Thanks Aamir, clarified! :+1:

**Comment by aamirshah** [comment]
@jojoyuji  Grunt has been permanently removed. Try updating Boom :)

**Comment by jojoyuji** [comment]
great! Pulling it :D
