### ISSUE TITLE
Generator attempted to install angular-utils

### ISSUE THREAD

**Issue by neilff** [aamirshah/generator-boom#4]
The generator was attempting to install angular-utils when I believe the intent is to install angular-ui-utils. I saw the issue in the bower.json file it generated and fixed the issue manually.

**Comment by aamirshah** [comment]
Thanks for finding the bug. I'll surely look into this and get back to you.

**Comment by aamirshah** [comment]
With [this commit](https://github.com/aamirshah/generator-boom/commit/1e498f2ef649e0d22eb6eb19ce903507d6c3c593) the issue is fixed.

Don't forget to update boom to 0.1.6
