### ISSUE TITLE
bower.js: invalid name for angular ui grid dependency

### ISSUE THREAD

**Issue by Redhab** [aamirshah/generator-boom#5]
bower.js uses "angular-ng-grid" instead of "ng-grid".

**Comment by aamirshah** [comment]
Thanks for pointing it out, I'll definitely fix it in the next commit.

**Comment by aamirshah** [comment]
With this commit https://github.com/aamirshah/generator-boom/commit/4a241bf26c39b5c1e923401cf051471624d4ba92 the bug is fixed.

Don't forget to update Boom to 0.1.7
