### ISSUE TITLE
Why do you have any grunt tasks?

### ISSUE THREAD

**Issue by deiga** [aamirshah/generator-boom#6]
AFAIK all these grunt tasks can be written with gulp, why use two build tools?

**Comment by aamirshah** [comment]
Nope. There is no plugin for gulp to do a `bower_concat` Grunt is used only to compile all the bower modules into one single file. Any Suggestions ?

**Comment by deiga** [comment]
https://www.npmjs.org/package/gulp-concat with https://github.com/ck86/gulp-bower-files maybe?

**Comment by aamirshah** [comment]
Good suggestion. Thanks. But there is issue with how to specify dependencies. You can have a look the way [Grunt](https://www.npmjs.org/package/grunt-bower-concat) does this.

I've also raised an [issue](https://github.com/ck86/gulp-bower-files/issues/32) for gulp-bower-files.

Any further suggestions ?

**Comment by ck86** [comment]
Everything what you can do with grunt-bower-concat you can do with gulp-bower-files.

**Comment by aamirshah** [comment]
@ck86 Any examples? I'm not clear how to specify dependencies in `gulp-bower-files`

**Comment by jdachtera** [comment]
@aamirshah you can put the dependencies and overrides it in the project's main bower.json like that:

```
{
    "name": "your-package-name",
    "dependencies": {
        "BOWER-PACKAGE": "*"
    },
    "overrides": {
        "BOWER-PACKAGE": {
            // Here you can override the main files or ignoring this package, for more info see options
        }
    }
}
```

then in gulpfile.js:

```
  var gulpFilter = require('gulp-filter'),
        gulpBowerFiles = require('gulp-bower-files'),
        jsFilter = gulpFilter('**/*.js'),
        cssFilter = gulpFilter('**/*.css');

    gulp.task('concat:lib', function() {
        gulpBowerFiles()
            .pipe(jsFilter)
            .pipe(concat("_bower.js"))
            .pipe(gulpif(isProduction, uglify()))
            .pipe(gulp.dest(settings.build.js))
            .pipe(jsFilter.restore())
            .pipe(cssFilter)
            .pipe(concat("_bower.css"))
            .pipe(gulp.dest(settings.build.css))
            .pipe(cssFilter.restore())
            .pipe(refresh(livereload));
    });
```

**Comment by aamirshah** [comment]
@jdachtera :+1: 

With https://github.com/aamirshah/generator-boom/commit/7712d7cf46b9f7f547cc0edb7a8b24e5e0cf5bdc commit its fixed now.
