### ISSUE TITLE
Bower components and CSS imports

### ISSUE THREAD

**Issue by deiga** [aamirshah/generator-boom#8]
How should one integrate bower_components css files into the workflow? I'm pretty sure manual isn't the right way to go :)

**Comment by aamirshah** [comment]
Any suggestions ? I'd prefer if there is any Gulp Plugin.

**Comment by deiga** [comment]
I solved this by making an `cssToInject` array that includes all the the paths to bower components CSS files and added a `copy:css:bower` task which copies these files into build.css before concatenate.

Not sure if theres a plugin

**Comment by deiga** [comment]
Here are possible plugins to do the trick better:
- [gulp-bower-src](https://github.com/bclozel/gulp-bower-src)
- [gulp-bower-files](https://github.com/ck86/gulp-bower-files)
- [gulp-include-source](https://github.com/gil/gulp-include-source)

**Comment by aamirshah** [comment]
@deiga This needs work. Right now I'm not getting enough time to work on this. It would be awesome if you can PR
